ALTER TABLE team_table ADD COLUMN Email VARCHAR(100);

CREATE TABLE otp_tokens_table (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Recipient VARCHAR(100) NOT NULL,
  ContactType ENUM('phone', 'email') NOT NULL DEFAULT 'email',
  OTPHash VARCHAR(255) NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  Verified TINYINT(1) DEFAULT 0,
  IsActive TINYINT(1) DEFAULT 1,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
